name: Build and Release Go executable

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'  # Adjust Go version as needed

      - name: Run tests
        run: |
          make go-test

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o universal-checksum-patcher.exe

      - name: Upload executable to release
        uses: softprops/action-gh-release@v2
        with:
          files: universal-checksum-patcher.exe
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}